// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NostrBot.Web.Storage;

#nullable disable

namespace NostrBot.Web.Storage.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("NostrBot.Web.Storage.ProcessedEvent", b =>
                {
                    b.Property<long>("ProcessedEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedReply")
                        .HasColumnType("TEXT");

                    b.Property<string>("NostrEventContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NostrEventCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NostrEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NostrEventKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NostrEventPubkey")
                        .HasColumnType("TEXT");

                    b.Property<string>("NostrEventTagE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NostrEventTagP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyContextId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subscription")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessedEventId");

                    b.ToTable("ProcessedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
